<a href="https://www.kaggle.com/code/anivana/nlp-practice-notebook?scriptVersionId=115712492" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import spacy

In [2]:
nlp = spacy.load("en_core_web_sm")
doc = nlp("Elon flew to mars yesterday. He carried biryani masala with him")

for token in doc:
    print(token," | ", token.pos_, " | ", spacy.explain(token.pos_))


Elon  |  PROPN  |  proper noun
flew  |  VERB  |  verb
to  |  ADP  |  adposition
mars  |  NOUN  |  noun
yesterday  |  NOUN  |  noun
.  |  PUNCT  |  punctuation
He  |  PRON  |  pronoun
carried  |  VERB  |  verb
biryani  |  ADJ  |  adjective
masala  |  NOUN  |  noun
with  |  ADP  |  adposition
him  |  PRON  |  pronoun


In [3]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [4]:
text = """
Inflation rose again in April, continuing a climb that has pushed consumers to the brink and is threatening the economic expansion, the Bureau of Labor Statistics reported Wednesday.

The consumer price index, a broad-based measure of prices for goods and services, increased 8.3% from a year ago, higher than the Dow Jones estimate for an 8.1% gain. That represented a slight ease from March’s peak but was still close to the highest level since the summer of 1982.

Removing volatile food and energy prices, so-called core CPI still rose 6.2%, against expectations for a 6% gain, clouding hopes that inflation had peaked in March.

The month-over-month gains also were higher than expectations — 0.3% on headline CPI versus the 0.2% estimate and a 0.6% increase for core, against the outlook for a 0.4% gain.

The price gains also meant that workers continued to lose ground. Real wages adjusted for inflation decreased 0.1% on the month despite a nominal increase of 0.3% in average hourly earnings. Over the past year, real earnings have dropped 2.6% even though average hourly earnings are up 5.5%.

Inflation has been the single biggest threat to a recovery that began early in the Covid pandemic and saw the economy in 2021 stage its biggest single-year growth level since 1984. Rising prices at the pump and in grocery stores have been one problem, but inflation has spread beyond those two areas into housing, auto sales and a host of other areas.

Federal Reserve officials have responded to the problem with two interest rate hikes so far this year and pledges of more until inflation comes down to the central bank’s 2% goal. However, Wednesday’s data shows that the Fed has a big job ahead.

Credits: cnbc.com
"""

In [5]:
doc = nlp(text)

for token in doc:
    print(token," | ", token.pos_, " | ", spacy.explain(token.pos_))



  |  SPACE  |  space
Inflation  |  PROPN  |  proper noun
rose  |  VERB  |  verb
again  |  ADV  |  adverb
in  |  ADP  |  adposition
April  |  PROPN  |  proper noun
,  |  PUNCT  |  punctuation
continuing  |  VERB  |  verb
a  |  DET  |  determiner
climb  |  NOUN  |  noun
that  |  PRON  |  pronoun
has  |  AUX  |  auxiliary
pushed  |  VERB  |  verb
consumers  |  NOUN  |  noun
to  |  ADP  |  adposition
the  |  DET  |  determiner
brink  |  NOUN  |  noun
and  |  CCONJ  |  coordinating conjunction
is  |  AUX  |  auxiliary
threatening  |  VERB  |  verb
the  |  DET  |  determiner
economic  |  ADJ  |  adjective
expansion  |  NOUN  |  noun
,  |  PUNCT  |  punctuation
the  |  DET  |  determiner
Bureau  |  PROPN  |  proper noun
of  |  ADP  |  adposition
Labor  |  PROPN  |  proper noun
Statistics  |  PROPN  |  proper noun
reported  |  VERB  |  verb
Wednesday  |  PROPN  |  proper noun
.  |  PUNCT  |  punctuation


  |  SPACE  |  space
The  |  DET  |  determiner
consumer  |  NOUN  |  noun
price  |  NOU

In [6]:
filtered_tokens = []
nn = []
for token in doc:
    if token.pos_ in ["NOUN"]:
        filtered_tokens.append(token)
    elif token.pos_ in ["NUM"]:
        nn.append(token)

In [7]:
filtered_tokens

[climb,
 consumers,
 brink,
 expansion,
 consumer,
 price,
 index,
 measure,
 prices,
 goods,
 services,
 %,
 year,
 estimate,
 %,
 gain,
 ease,
 peak,
 level,
 summer,
 food,
 energy,
 prices,
 core,
 %,
 expectations,
 %,
 gain,
 hopes,
 inflation,
 month,
 month,
 gains,
 expectations,
 %,
 headline,
 %,
 estimate,
 %,
 increase,
 core,
 outlook,
 %,
 gain,
 price,
 gains,
 workers,
 ground,
 wages,
 inflation,
 %,
 month,
 increase,
 %,
 earnings,
 year,
 earnings,
 %,
 earnings,
 %,
 Inflation,
 threat,
 recovery,
 economy,
 year,
 growth,
 level,
 prices,
 pump,
 grocery,
 stores,
 problem,
 inflation,
 areas,
 housing,
 auto,
 sales,
 host,
 areas,
 officials,
 problem,
 interest,
 rate,
 year,
 pledges,
 inflation,
 %,
 goal,
 data,
 job,
 Credits]

In [8]:
nn

[8.3,
 8.1,
 1982,
 6.2,
 6,
 0.3,
 0.2,
 0.6,
 0.4,
 0.1,
 0.3,
 2.6,
 5.5,
 2021,
 1984,
 one,
 two,
 two,
 2]

In [9]:
count = doc.count_by(spacy.attrs.POS)
count

{103: 9,
 96: 19,
 100: 29,
 86: 15,
 85: 39,
 97: 32,
 90: 34,
 92: 91,
 95: 4,
 87: 13,
 89: 10,
 84: 23,
 93: 19,
 94: 4,
 98: 8,
 101: 1}

In [10]:
for k,v in count.items():
    print(doc.vocab[k].text, "|",v)

SPACE | 9
PROPN | 19
VERB | 29
ADV | 15
ADP | 39
PUNCT | 32
DET | 34
NOUN | 91
PRON | 4
AUX | 13
CCONJ | 10
ADJ | 23
NUM | 19
PART | 4
SCONJ | 8
X | 1


In [11]:
print('hi')

hi


In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv("/kaggle/input/spam-email/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [14]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [15]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [16]:
df.shape

(5572, 3)

In [17]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [19]:
X_train.shape

(4457,)

In [20]:
X_test.shape

(1115,)

In [21]:
type(X_train)

pandas.core.series.Series

In [22]:
X_train[:4]

2326                             Apps class varaya elaya.
888     Y dun cut too short leh. U dun like ah? She fa...
1028          Are you not around or just still asleep? :V
747     I promise to take good care of you, princess. ...
Name: Message, dtype: object

In [23]:
type(y_train)

pandas.core.series.Series

In [24]:
y_train[:4]

2326    0
888     0
1028    0
747     0
Name: spam, dtype: int64

In [25]:
type(X_train.values)

numpy.ndarray

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7766 sparse matrix of type '<class 'numpy.int64'>'
	with 58834 stored elements in Compressed Sparse Row format>

In [27]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
X_train_cv.shape

(4457, 7766)

In [29]:
v.get_feature_names_out()[1771]

'chg'

In [30]:
v.vocabulary_

{'apps': 1035,
 'class': 1819,
 'varaya': 7263,
 'elaya': 2554,
 'dun': 2481,
 'cut': 2125,
 'too': 6990,
 'short': 6129,
 'leh': 4077,
 'like': 4116,
 'ah': 870,
 'she': 6090,
 'failed': 2751,
 'quite': 5543,
 'sad': 5891,
 'are': 1049,
 'you': 7727,
 'not': 4827,
 'around': 1069,
 'or': 4985,
 'just': 3874,
 'still': 6500,
 'asleep': 1100,
 'promise': 5465,
 'to': 6954,
 'take': 6711,
 'good': 3181,
 'care': 1654,
 'of': 4897,
 'princess': 5425,
 'have': 3352,
 'run': 5874,
 'now': 4841,
 'please': 5260,
 'send': 6027,
 'pics': 5216,
 'when': 7498,
 'get': 3114,
 'chance': 1719,
 'ttyl': 7087,
 'life': 4105,
 'style': 6565,
 'garments': 3076,
 'account': 784,
 'no': 4794,
 'it': 3754,
 'in': 3633,
 'is': 3743,
 'that': 6829,
 'ok': 4923,
 'all': 911,
 'these': 6853,
 'nice': 4771,
 'new': 4760,
 'shirts': 6112,
 'and': 963,
 'the': 6833,
 'only': 4954,
 'thing': 6862,
 'can': 1629,
 'wear': 7436,
 'them': 6842,
 'nudist': 4854,
 'themed': 6843,
 'mu': 4636,
 'thk': 6874,
 '530': 551,

In [31]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
np.where(X_train_np[0]!=0)

(array([1035, 1819, 2554, 7263]),)

In [33]:
X_train[:][849]

"Yeah there's barely enough room for the two of us, x has too many fucking shoes. Sorry man, see you later"

In [34]:
X_train_np[0][1771]

0